### ISSUE TITLE
get_attribute fails on empty arrays

### ISSUE THREAD

**Issue by jeffwarnica** [syncrou/manageiq-automate#3]
In CF I'm doing 
@handle.root['a_groups'] = groups

where groups could be an empty array ( [] )

embedded ansible in verbose mode shows this as expected, e.g.:

```

                "/ManageIQ/System/event_handlers/event_enforce_policy": {
                    "::miq::parent": "/ManageIQ/System/Event/MiqEvent/POLICY/request_vm_retire"
                },
                "root": {
                    **"a_groups": [],**
                    "a_platform": "linux",
                    "ae_next_state": "",
                    "ae_provider_category": "infrastructure",
                    "ae_result": "ok",
                    "ae_retry_server_affinity": false,
                    "ae_state": "AnsibleRetire1",
                    "ae_state_max_retries": 100,
```

but then the obvious call:
```
  tasks:
    - name: Get $evm.root['a_groups']
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:
          object: "root"
          attribute: "a_groups"
      register: a_groups
```

fails with
`Object root Attribute a_groups does not exist`

unless
`      ignore_errors: True`

(but  even then, special care must be taken to not operate on a non-existant fact in the playbook)
